# fly.toml app configuration file generated for daruma-small-moon-5764-lingering-paper-3727-rough-cherry-3483 on 2024-03-06T16:29:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'darumapi'
primary_region = 'mad'

[build]
  image = 'maven:3.8.4-openjdk-17'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[services]]
    internal_port = 4000
    protocol = "tcp"
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0


[[services.ports]]
    port = 4000
    handlers = ['http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
